language: go

go:
  - 1.x

branches:
  only:
  - master

addons:
  apt:
    packages:
    - moreutils

install:
  - make get-tools
  - make get-deps

# script:
#   - make

stages:
    - name: test
    - name: build

jobs:
  include:
    - stage: test
      name: "Check Tests"
      script: make
    - stage: build
      name: "Build Tests"
      # install: make get-tools && make get-deps
      script: make build && make package
      # TODO: publish after success only on tag
      # after_success:
      #   - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      #        make publish
      #     fi
