language: go
go:
  - 1.x

addons:
  apt:
    packages:
    - moreutils

install:
  - make get-tools
  - make get-deps

script:
  - make

jobs:
  include:
    - stage: Build Tests
      install: make get-tools && make get-deps
      script: make build && make package
